services:
  real-esrgan:
    build:
      context: .
    image: trixie-slim:uv-nvm
    container_name: real-esrgan
    working_dir: /root/real-esrgan
    environment:
      - DISPLAY=${DISPLAY:-host.docker.internal:0}
      - QT_X11_NO_MITSHM=1
    volumes:
      - .:/root/real-esrgan
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    ipc: host
    tty: true

  real-esrgan-gpu:
    extends:
      service: real-esrgan
    container_name: real-esrgan-gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    profiles:
      - gpu